unused = false
new_globals = {
    "OLUA_AUTO_BUILD",
    "OLUA_AUTO_GEN_PROP",
    "OLUA_AUTO_EXPORT_PARENT",
    "OLUA_ENABLE_WITH_UNDERSCORE",
    "OLUA_ENABLE_DEPRECATED",
    "OLUA_MAX_VARIADIC_ARGS",
    "OLUA_VERBOSE",
    "LUA_DEBUG",
    "autoconf",
    "chunk",
    "name",
    "clang",
    "dofile",
    "excludetype",
    "export",
    "headers",
    "include",
    "import",
    "ipairs",
    "luacls",
    "luaopen",
    "macro",
    "olua",
    "pairs",
    "path",
    "typeconf",
    "typedef",
    "typeonly",
}
ignore = {"212", "611", "631"}